tasks:
  - name: Plutus Server Start
    init: >
        curl -L https://nixos.org/nix/install | sh && 
        git clone https://github.com/input-output-hk/plutus-apps &&
        gp sync-done initial
    command: >
        cat /etc/nix/nix.conf &&
        sudo -i &&
        echo -e "substituters = https://hydra.iohk.io https://iohk.cachix.org https://cache.nixos.org/ trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=" > /etc/nix/nix.conf &&
        exit &&
        cd ~/plutus-apps &&
        nix-shell &&
        cd plutus-playground-server &&
        GC_DONT_GC=1 nix-build -A plutus-playground.server
  - name: Plutus Client Start
    init: gp sync-await initial 
    command: >
        cd ~/plutus-apps && 
        nix-shell && 
        cd plutus-playground-client &&
        npm run start